import type { MemberRoleType, CarType } from '@/views/apps/menu/vehicules/types'
import { TbBriefcase, TbCode, TbHeadset, TbShieldLock } from 'react-icons/tb'

import user1 from '@/assets/images/users/user-1.jpg'
import user10 from '@/assets/images/users/user-10.jpg'
import user2 from '@/assets/images/users/user-2.jpg'
import user3 from '@/assets/images/users/user-3.jpg'
import user4 from '@/assets/images/users/user-4.jpg'
import user5 from '@/assets/images/users/user-5.jpg'
import user6 from '@/assets/images/users/user-6.jpg'
import user7 from '@/assets/images/users/user-7.jpg'
import user8 from '@/assets/images/users/user-8.jpg'
import user9 from '@/assets/images/users/user-9.jpg'

export const memberRoles: MemberRoleType[] = [
  {
    id: 1,
    title: 'Security Officer',
    description: 'Handles platform safety and protocol reviews.',
    icon: TbShieldLock,
    features: ['Daily Risk Assessment', 'Manage Security Logs', 'Control Access Rights', 'Emergency Protocols'],
    users: [user7, user8, user9, user10],
    updatedTime: '1 hour ago',
  },
  {
    id: 2,
    title: 'Project Manager',
    description: 'Coordinates planning and team delivery timelines.',
    icon: TbBriefcase,
    features: ['Timeline Tracking', 'Task Assignments', 'Budget Control', 'Stakeholder Reporting'],
    users: [user2, user5, user6, user1, user8],
    updatedTime: '2 hours ago',
  },
  {
    id: 3,
    title: 'Developer',
    description: 'Builds and maintains the platform core features.',
    icon: TbCode,
    features: ['Codebase Maintenance', 'API Integration', 'Unit Testing', 'Feature Deployment'],
    users: [user3, user4, user9, user10, user8, user1],
    updatedTime: '3 hours ago',
  },
  {
    id: 4,
    title: 'Support Lead',
    description: 'Oversees customer support and service quality.',
    icon: TbHeadset,
    features: ['Respond to Tickets', 'Live Chat Supervision', 'FAQ Updates', 'Support Metrics Review'],
    users: [user1, user5, user7],
    updatedTime: '30 min ago',
  },
]
//  (3.5T/10T/19T/Tracteur
export const cars: CarType[] = [
  {
    id: '#USR00123',
    name: 'Youssef Alami',
    email: 'youssef.alami@eurofast.ma',
    avatar: user5,
    role: 'Project Manager',
    tonnage: "3.5 T",
    capacite: "capaciteM3",
    date: '18 Apr, 2025',
    time: '9:45 AM',
    proprietaire: 'Eurofat',
    n_vehicule: '101',
    immatriculation: 'AB-234-CD',
    type: 'Fourgon léger',
  },
  {
    id: '#USR00145',
    name: 'Fatima Zahra Benjelloun',
    email: 'fatima.benjelloun@eurofast.ma',
    capacite: "capaciteM3",
    avatar: user3,
    tonnage: "10 T",

    role: 'Developer',
    date: '21 Apr, 2025',
    time: '3:15 PM',
    proprietaire: 'Eurofat',
    n_vehicule: '102',
    immatriculation: 'EF-567-GH',
    type: 'Camionnette',
  },
  {
    id: '#USR00162',
    name: 'Amina Tazi',
    email: 'amina.tazi@eurofast.ma',
    capacite: "capaciteM3",
    avatar: user1,
    tonnage: "19 T",
    role: 'Support Lead',
    date: '19 Apr, 2025',
    time: '10:00 AM',
    proprietaire: 'societe externe',
    n_vehicule: '103',
    immatriculation: 'IJ-891-KL',
    type: 'Mini-van de livraison',
  },
  {
    id: '#USR00178',
    name: 'Omar Berrada',
    email: 'omar.berrada@eurofast.ma',
    tonnage: "3.5 T",
    avatar: user2,
    role: 'Developer',
    capacite: "capaciteM3",
    date: '22 Apr, 2025',
    time: '8:15 AM',
    proprietaire: 'Eurofat',
    n_vehicule: '104',
    immatriculation: 'MN-345-OP',
    type: 'Pick-up utilitaire',
  },
  {
    id: '#USR00189',
    name: 'Layla El Idrissi',
    email: 'layla.elidrissi@eurofast.ma',
    avatar: user4,
    tonnage: "10 T",
    proprietaire: "Eurofat",
    role: 'Security Officer',
    capacite: "capaciteM3",
    date: '20 Apr, 2025',
    time: '2:45 PM',
    type: 'Fourgon léger',
    n_vehicule: '105',
    immatriculation: 'QR-678-ST',
  },
  {
    id: '#USR00203',
    name: 'Karim Bennani',
    email: 'karim.bennani@eurofast.ma',
    tonnage: "19 T",
    avatar: user6,
    type: "Tracteur",
    role: 'Support Lead',
    capacite: "capaciteM3",
    date: '15 Apr, 2025',
    time: '11:20 AM',
    proprietaire: 'Eurofat',
    n_vehicule: '106',
    immatriculation: 'UV-912-WX',
  },
  {
    id: '#USR00215',
    name: 'Salma Chaoui',
    email: 'salma.chaoui@eurofast.ma',
    tonnage: "10 T",
    avatar: user8,
    capacite: "societe externe",
    role: 'Developer',
    date: '23 Apr, 2025',
    time: '4:25 PM',
    proprietaire: 'societe externe',
    n_vehicule: '107',
    immatriculation: 'YZ-456-AB',
    type: 'Mini-van de livraison',
  },
  {
    id: '#USR00228',
    name: 'Mehdi Fassi',
    email: 'mehdi.fassi@eurofast.ma',
    capacite: "capaciteM3",
    tonnage: "3.5 T",
    avatar: user9,
    role: 'Security Officer',
    date: '17 Apr, 2025',
    time: '6:10 PM',
    proprietaire: 'Eurofat',
    n_vehicule: '108',
    immatriculation: 'CD-789-EF',
    type: 'Pick-up utilitaire',
  },
  {
    id: '#USR00239',
    name: 'Hajar Mansouri',
    email: 'hajar.mansouri@eurofast.ma',
    tonnage: "3.5 T",
    capacite: "capaciteM3",
    avatar: user10,
    role: 'Project Manager',
    date: '11 Apr, 2025',
    time: '1:30 PM',
    proprietaire: 'societe externe',
    n_vehicule: '109',
    immatriculation: 'GH-123-IJ',
    type: 'Fourgon léger',
  },
]
